repos:
# - hooks:
#   - id: commitizen
#   - id: commitizen-branch
#   stages:
#     - push
#   repo: https://github.com/commitizen-tools/commitizen
#   rev: v2.40.0
- repo: https://github.com/golangci/golangci-lint
  rev: v1.51.2
  hooks:
  - id: golangci-lint
