name: CICD pipeline
on: 
  push: 
    branches:
      - *
  pull_request: 
    branches:
      - *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: install deps
        run: | 
          go mod vendor
      - name: build
        run: go build .
      - name: test
        run: go test ./...